### ISSUE TITLE
[Bug] Clone fails in Windows environment

### ISSUE THREAD

**Issue by ensan-hcl** [ensan-hcl/azooKey_dictionary_storage#1]
どうやら全角空白が先頭に入っているとcloneが上手くいかないっぽい。元々使われていないファイルなので、消す
https://github.com/ensan-hcl/AzooKeyKanaKanjiConverter/pull/61

**Comment by fkunn1326** [comment]
![image](https://github.com/ensan-hcl/azooKey_dictionary_storage/assets/92153597/f2ca6bf9-3d15-43fe-88b2-892e372e6c78)
![image](https://github.com/ensan-hcl/azooKey_dictionary_storage/assets/92153597/3bdb5be8-a8aa-4ffe-a1cd-507b7a059662)

全角空白以外にも `".loads`とかが引っ掛かりますね

**Comment by ensan-hcl** [comment]
ありがとうございます！これ近く対応します！

**Comment by ensan-hcl** [comment]
ダブルクオーテーションも引っかかるのか、ダブルクオーテーションは消すだけではダメなので少し厄介ですね。

**Comment by ensan-hcl** [comment]
#3 で最終的に解決したと思います。
